In [12]:
import cv2
import numpy as np
from tqdm import tqdm

layer0 = cv2.imread('layer0.png')
layer0 = cv2.cvtColor(layer0, cv2.COLOR_BGR2GRAY)
print(layer0)
print(layer0.shape)
layer1 = cv2.imread('layer1.png')
layer1 = cv2.cvtColor(layer1, cv2.COLOR_BGR2GRAY)
layer2 = cv2.imread('layer2.png')
layer2 = cv2.cvtColor(layer2, cv2.COLOR_BGR2GRAY)


[[  0   0   0 ...   0   0 200]
 [  0   0   0 ...   0   0 255]
 [  0   0   0 ... 255 255 255]
 ...
 [200   0 255 ...   0   0 255]
 [  0   0   0 ...   0   0 255]
 [200 255 255 ... 255 255 255]]
(4000, 4000)


In [13]:
layer = np.array([layer0, layer1, layer2])
print(layer.shape)

(3, 4000, 4000)


In [14]:
starting_points = []

In [15]:
for i in range(4000):
    for j in range(4000):
        if layer0[i,j]==200 and layer1[i,j]==200:
            starting_points.append((i,j))

In [16]:
print(len(starting_points))
print(starting_points[0])
print(starting_points[0][1])

110220
(0, 46)
46


In [18]:
counter_list=[]
for t in tqdm(range(len(starting_points))):
    x = starting_points[t][0]
    y = starting_points[t][1]
    z=0
    stop=0
    counter=0
    check = 0
    pos_list=[]

    while check<5:
        # print(counter)
        moved=0
        
        ### x increases xxx +++
        if x<3999 and (z,x+1,y) not in pos_list:
            # print("x<4000")
            if layer[z,x+1,y] == 255 and moved==0:
                x +=1
                counter +=1
                moved=1
                # print("255")

            if moved==0 and layer[z,x+1,y] == 200: 
                x +=1
                counter +=1
                moved=1
                # print("200")
                if z==0:
                    if layer[z+1,x,y] == 200 and (z+1,x,y) not in pos_list:
                        z +=1
                if z==1:
                    if layer[z-1,x,y] == 200 and (z-1,x,y) not in pos_list:
                        z -=1
    
                    if layer[z+1,x,y] == 200 and (z+1,x,y) not in pos_list:
                        z +=1
                if z==2:
                    if layer[z-1,x,y] == 200 and (z-1,x,y) not in pos_list:
                        z -=1
    

        if y<3999 and (z,x,y+1) not in pos_list:
            # print("y<4000")
            if layer[z,x,y+1] == 255 and moved==0:
                y +=1
                counter +=1
                moved=1
                # print("255")
            if moved ==0 and layer[z,x,y+1] == 200: 
                y +=1
                counter +=1
                moved=1
                # print("200")
                if z==0:
                    if layer[z+1,x,y] == 200 and (z+1,x,y) not in pos_list:
                        z +=1
                if z==1:
                    if layer[z-1,x,y] == 200 and (z-1,x,y) not in pos_list:
                        z -=1
    
                    if layer[z+1,x,y] == 200 and (z+1,x,y) not in pos_list:
                        z +=1
                if z==2:
                    if layer[z-1,x,y] == 200 and (z-1,x,y) not in pos_list:
                        z -=1
    

        if x>0 and (z,x-1,y) not in pos_list:
            # print("x>0")
            if layer[z,x-1,y] == 255 and moved==0:
                x -=1
                counter +=1
                moved=1
                # print("255")
            if moved ==0 and layer[z,x-1,y] == 200: #change layer for x-1
                x -=1
                counter +=1
                moved=1
                # print("200")
                if z==0:
                    if layer[z+1,x,y] == 200 and (z+1,x,y) not in pos_list:
                        z +=1
                if z==1:
                    if layer[z-1,x,y] == 200 and (z-1,x,y) not in pos_list:
                        z -=1
                    if layer[z+1,x,y] == 200 and (z+1,x,y) not in pos_list:
                        z +=1
                if z==2:
                    if layer[z-1,x,y] == 200 and (z-1,x,y) not in pos_list:
                        z -=1
    

        if y>0 and (z,x,y-1) not in pos_list:
            # print("y>0")
            if layer[z,x,y-1] == 255 and moved==0:
                y -=1
                counter +=1
                moved=1
                # print("255")
            if moved ==0 and layer[z,x,y-1] == 200: #change layer for y-1
                y -=1
                counter +=1
                moved=1
                # print("200")
                if z==0:
                    if layer[z+1,x,y] == 200 and (z+1,x,y) not in pos_list:
                        z +=1
                if z==1:
                    if layer[z-1,x,y] == 200 and (z-1,x,y) not in pos_list:
                        z -=1
    
                    if layer[z+1,x,y] == 200 and (z+1,x,y) not in pos_list:
                        z +=1
                if z==2:
                    if layer[z-1,x,y] == 200 and (z-1,x,y) not in pos_list:
                        z -=1
    

        if (z,x,y) in pos_list:
            check +=1

        pos_list.append((z,x,y))

    counter_list.append(counter)


100%|██████████| 110220/110220 [01:43<00:00, 1063.92it/s]


In [19]:
print(max(counter_list))

702
